version: "3.8"
services:

  kafka-app:
    image: kafka-app
    ports:
        - "8080:8080"
    network_mode: "host"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    network_mode: "host"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  kafkaserver:
    image: kafkaserver
    ports:
      - "9092:9092"
    network_mode: "host"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure